const data = [
  {
    id: 1,
    name: "Myntra - Fashion Shopping App",
    description: "com.myntra.android",
    platforms: ["android"],
    status: "Active",
    count: "1",
    totalClicks: "14.7M",
    totalInstalls: "4.2M",
    totalEvents: "20K",
    clickCount: "18.34%",
    installsCount: "8.16%",
    eventCount: "2.84%",
    clickStatus: "up",
    installsStatus: "up",
    eventStatus: "up",
    logo: require("./image/mytra.png"),
  },
  {
    id: 2,
    name: "Shopping Link",
    description: "Shopping campaign for web users",
    platforms: ["android"],
    status: "Active",
    count: "2",
    totalClicks: "24.1M",
    totalInstalls: "10K",
    totalEvents: "15K",
    clickCount: "21.03%",
    installsCount: "16.11%",
    eventCount: "3.64%",
    clickStatus: "up",
    installsStatus: "up",
    eventStatus: "up",
    logo: require("./image/live.png"),
  },
  {
    id: 3,
    name: "News Application",
    description: "News app promotion campaign",
    platforms: ["chrome"],
    status: "Paused",
    count: "11",
    totalClicks: "1.6M",
    totalInstalls: "9K",
    totalEvents: "12K",
    clickCount: "8.93%",
    installsCount: "8.16%",
    eventCount: "3.12%",
    clickStatus: "down",
    installsStatus: "up",
    eventStatus: "up",
    logo: require("./image/noon.png"),
  },
  {
    id: 4,
    name: "Tiktoxid",
    description: "Social media campaign",
    platforms: ["apple"],
    status: "Inactive",
    count: "3",
    totalClicks: "7.0M",
    totalInstalls: "85K",
    totalEvents: "45K",
    clickCount: "3.17%",
    installsCount: "7.40%",
    eventCount: "4.83%",
    clickStatus: "down",
    installsStatus: "down",
    eventStatus: "down",
    logo: require("./image/takelot.png"),
  },
  {
    id: 5,
    name: "London Mobile",
    description: "Local mobile campaign",
    platforms: ["android", "apple"],
    status: "Paused",
    count: "5",
    totalClicks: "76.0M",
    totalInstalls: "66.2M",
    totalEvents: "5.2K",
    clickCount: "18.34%",
    installsCount: "8.16%",
    eventCount: "6.23%",
    clickStatus: "up",
    installsStatus: "up",
    eventStatus: "up",
    logo: require("./image/lazada.png"),
  },
  {
    id: 6,
    name: "Amazon Mobile LLC",
    description: "E-commerce mobile campaign",
    platforms: ["android", "apple", "chrome"],
    status: "Inactive",
    count: "1",
    totalClicks: "14.7M",
    totalInstalls: "4.2M",
    totalEvents: "5.2K",
    clickCount: "12.62%",
    installsCount: "22.63%",
    eventCount: "45.32%",
    clickStatus: "down",
    installsStatus: "down",
    eventStatus: "down",
    logo: require("./image/amazon.png"),
  },
  {
    id: 7,
    name: "KFC",
    description: "Food delivery campaign",
    platforms: ["android"],
    status: "Active",
    count: "21",
    totalClicks: "14.7M",
    totalInstalls: "4.2M",
    totalEvents: "5.2K",
    clickCount: "12.62%",
    installsCount: "22.63%",
    eventCount: "45.32%",
    clickStatus: "up",
    installsStatus: "up",
    eventStatus: "down",
    logo: require("./image/kfc.png"),
  },
];
export default data;
